git-debimport ocfs2-tools_1.6.4.orig.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -848,7 +848,7 @@ Optional Features:
   --enable-debugexe=yes/no     Enable debug executables for library source files default=no
   --disable-glibtest      do not try to compile and run a test GLIB program
   --enable-dynamic-fsck=yes/no    Build fsck dynamically default=no
-  --enable-dynamic-ctl=yes/no    Build cluster control tools dynamically default=test
+  --enable-dynamic-ctl=yes/no    Build cluster control tools dynamically default=no
   --enable-ocfs2console=yes/no    Build GUI frontend default=yes
 
 Optional Packages:
@@ -1311,7 +1311,7 @@ PACKAGE=ocfs2-tools
 
 # Adjust these for the software version.
 MAJOR_VERSION=1
-MINOR_VERSION=4
+MINOR_VERSION=6
 MICRO_VERSION=4
 EXTRA_VERSION=
 
@@ -4451,62 +4451,32 @@ echo "$as_me: error: GLib $GLIB_REQUIRED_VERSION or better is required" >&2;}
   rm -f conf.glibtest
 
 
-echo "$as_me:$LINENO: checking whether to build fsck dynamically" >&5
-echo $ECHO_N "checking whether to build fsck dynamically... $ECHO_C" >&6
-# Check whether --enable-dynamic-fsck or --disable-dynamic-fsck was given.
-if test "${enable_dynamic_fsck+set}" = set; then
-  enableval="$enable_dynamic_fsck"
 
-else
-  enable_dynamic_fsck=no
-fi;
-OCFS2_DYNAMIC_FSCK=
-if test "x$enable_dynamic_fsck" = "xyes"; then
-    OCFS2_DYNAMIC_FSCK=yes
-fi
+#
+# Can we build statically?  This is important
+#
+dyn_save_CFLAGS="$CFLAGS"
+dyn_save_LIBS="$LIBS"
+CFLAGS="$CFLAGS $GLIB_CFLAGS"
+LIBS="-static $LIBS $GLIB_LIBS $COM_ERR_LIBS"
 
-echo "$as_me:$LINENO: result: $enable_dynamic_fsck" >&5
-echo "${ECHO_T}$enable_dynamic_fsck" >&6
-
-OCFS2_DYNAMIC_CTL=
-echo "$as_me:$LINENO: checking whether to build cluster control tools dynamically" >&5
-echo $ECHO_N "checking whether to build cluster control tools dynamically... $ECHO_C" >&6
-# Check whether --enable-dynamic-ctl or --disable-dynamic-ctl was given.
-if test "${enable_dynamic_ctl+set}" = set; then
-  enableval="$enable_dynamic_ctl"
-
-echo "$as_me:$LINENO: result: $enable_dynamic_ctl" >&5
-echo "${ECHO_T}$enable_dynamic_ctl" >&6
-
-else
-
-enable_dynamic_ctl=test
-echo "$as_me:$LINENO: result: test" >&5
-echo "${ECHO_T}test" >&6
-fi;
-
-if test "x$enable_dynamic_ctl" = "xtest"; then
-  dyn_save_CFLAGS="$CFLAGS"
-  dyn_save_LIBS="$LIBS"
-  CFLAGS="$CFLAGS $GLIB_CFLAGS"
-  LIBS="-static $LIBS $GLIB_LIBS"
-
-  echo "$as_me:$LINENO: checking how to link o2cb_ctl" >&5
-echo $ECHO_N "checking how to link o2cb_ctl... $ECHO_C" >&6
-  cat >conftest.$ac_ext <<_ACEOF
+echo "$as_me:$LINENO: checking whether glib and com_err can be linked statically" >&5
+echo $ECHO_N "checking whether glib and com_err can be linked statically... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
+#include <et/com_err.h>
 #include <glib.h>
 #include <stdio.h>
 
 int
 main ()
 {
- return ((glib_major_version) || (glib_minor_version) || (glib_micro_version));
+ char *e = error_message(-1); return ((glib_major_version) || (glib_minor_version) || (glib_micro_version));
   ;
   return 0;
 }
@@ -4534,29 +4504,82 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-enable_dynamic_ctl=no
-echo "$as_me:$LINENO: result: static" >&5
-echo "${ECHO_T}static" >&6
+static_lib_link=yes
 
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 
-enable_dynamic_ctl=yes
-echo "$as_me:$LINENO: result: dynamic" >&5
-echo "${ECHO_T}dynamic" >&6
+static_lib_link=no
+
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $static_lib_link" >&5
+echo "${ECHO_T}$static_lib_link" >&6
 
-  CFLAGS="$dyn_save_CFLAGS"
-  LIBS="$dyn_save_LIBS"
+CFLAGS="$dyn_save_CFLAGS"
+LIBS="$dyn_save_LIBS"
+
+
+OCFS2_DYNAMIC_FSCK=
+echo "$as_me:$LINENO: checking whether to build fsck dynamically" >&5
+echo $ECHO_N "checking whether to build fsck dynamically... $ECHO_C" >&6
+# Check whether --enable-dynamic-fsck or --disable-dynamic-fsck was given.
+if test "${enable_dynamic_fsck+set}" = set; then
+  enableval="$enable_dynamic_fsck"
+
+else
+  enable_dynamic_fsck=detect
+fi;
+if test "x$enable_dynamic_fsck" = "xdetect"; then
+    if test "x$static_lib_link" = "xyes"; then
+        enable_dynamic_fsck=no
+    else
+        enable_dynamic_fsck=yes
+    fi
+fi
+echo "$as_me:$LINENO: result: $enable_dynamic_fsck" >&5
+echo "${ECHO_T}$enable_dynamic_fsck" >&6
+if test "x$static_lib_link" = "xno" -a "x$enable_dynamic_fsck" = "xno"; then
+    { { echo "$as_me:$LINENO: error: Unable to statically link fsck.ocfs2" >&5
+echo "$as_me: error: Unable to statically link fsck.ocfs2" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "x$enable_dynamic_fsck" = "xyes"; then
+    OCFS2_DYNAMIC_FSCK=yes
 fi
 
+
+OCFS2_DYNAMIC_CTL=
+echo "$as_me:$LINENO: checking whether to build cluster control tools dynamically" >&5
+echo $ECHO_N "checking whether to build cluster control tools dynamically... $ECHO_C" >&6
+# Check whether --enable-dynamic-ctl or --disable-dynamic-ctl was given.
+if test "${enable_dynamic_ctl+set}" = set; then
+  enableval="$enable_dynamic_ctl"
+
+else
+  enable_dynamic_ctl=detect
+fi;
+if test "x$enable_dynamic_ctl" = "xdetect"; then
+    if test "x$static_lib_link" = "xyes"; then
+        enable_dynamic_ctl=no
+    else
+        enable_dynamic_ctl=yes
+    fi
+fi
+echo "$as_me:$LINENO: result: $enable_dynamic_ctl" >&5
+echo "${ECHO_T}$enable_dynamic_ctl" >&6
+if test "x$static_lib_link" = "xno" -a "x$enable_dynamic_ctl" = "xno"; then
+    { { echo "$as_me:$LINENO: error: Unable to statically link cluster control tools" >&5
+echo "$as_me: error: Unable to statically link cluster control tools" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test "x$enable_dynamic_ctl" = "xyes"; then
     OCFS2_DYNAMIC_CTL=yes
 fi
+
 
 
 BUILD_DEBUGOCFS2=
@@ -5534,7 +5557,12 @@ if test "x$cpg_found" = "xyes"; then
 echo $ECHO_N "checking for cpg_initialize in -lcpg... $ECHO_C" >&6
     while test "x$TRY_PATH" != "x"; do
         TRY="`echo $TRY_PATH | cut -f1 -d:`"
-        TRY_PATH="`echo $TRY_PATH | cut -f2- -d:`"
+        NEW_TRY_PATH="`echo $TRY_PATH | cut -f2- -d:`"
+        if test "x$NEW_TRY_PATH" != "x$TRY_PATH"; then
+            TRY_PATH="$NEW_TRY_PATH"
+        else
+            TRY_PATH=""
+        fi
 
         if test "x$TRY" != "x"; then
             TRY="-L${TRY}/${cpg_package}"
@@ -5680,7 +5708,12 @@ if test "x$ckpt_found" = "xyes"; then
 echo $ECHO_N "checking for saCkptInitialize in -lSaCkpt... $ECHO_C" >&6
     while test "x$TRY_PATH" != "x"; do
         TRY="`echo $TRY_PATH | cut -f1 -d:`"
-        TRY_PATH="`echo $TRY_PATH | cut -f2- -d:`"
+        NEW_TRY_PATH="`echo $TRY_PATH | cut -f2- -d:`"
+        if test "x$NEW_TRY_PATH" != "x$TRY_PATH"; then
+            TRY_PATH="$NEW_TRY_PATH"
+        else
+            TRY_PATH=""
+        fi
 
         if test "x$TRY" != "x"; then
             TRY="-L${TRY}/openais"
@@ -8178,7 +8211,7 @@ fi
 
 
 
-                                                                                                                                                                                    ac_config_files="$ac_config_files Config.make o2cb.pc o2dlm.pc ocfs2.pc ocfs2console/ocfs2interface/confdefs.py debugfs.ocfs2/debugfs.ocfs2.8 mkfs.ocfs2/mkfs.ocfs2.8 mounted.ocfs2/mounted.ocfs2.8 fsck.ocfs2/fsck.ocfs2.8 fsck.ocfs2/fsck.ocfs2.checks.8 mount.ocfs2/mount.ocfs2.8 o2cb_ctl/o2cb_ctl.8 ocfs2_hb_ctl/ocfs2_hb_ctl.8 ocfs2console/ocfs2console.8 tunefs.ocfs2/tunefs.ocfs2.8 o2image/o2image.8 libo2cb/o2cb.7 vendor/common/ocfs2-tools.spec-generic"
+                                                                                                                                                                                              ac_config_files="$ac_config_files Config.make o2cb.pc o2dlm.pc ocfs2.pc ocfs2console/ocfs2interface/confdefs.py debugfs.ocfs2/debugfs.ocfs2.8 mkfs.ocfs2/mkfs.ocfs2.8 mounted.ocfs2/mounted.ocfs2.8 fsck.ocfs2/fsck.ocfs2.8 fsck.ocfs2/fsck.ocfs2.checks.8 mount.ocfs2/mount.ocfs2.8 o2cb_ctl/o2cb_ctl.8 ocfs2_hb_ctl/ocfs2_hb_ctl.8 ocfs2console/ocfs2console.8 tunefs.ocfs2/tunefs.ocfs2.8 o2image/o2image.8 o2info/o2info.1 libo2cb/o2cb.7 vendor/common/ocfs2-tools.spec-generic"
 
 
 cat >confcache <<\_ACEOF
@@ -8763,6 +8796,7 @@ do
   "ocfs2console/ocfs2console.8" ) CONFIG_FILES="$CONFIG_FILES ocfs2console/ocfs2console.8" ;;
   "tunefs.ocfs2/tunefs.ocfs2.8" ) CONFIG_FILES="$CONFIG_FILES tunefs.ocfs2/tunefs.ocfs2.8" ;;
   "o2image/o2image.8" ) CONFIG_FILES="$CONFIG_FILES o2image/o2image.8" ;;
+  "o2info/o2info.1" ) CONFIG_FILES="$CONFIG_FILES o2info/o2info.1" ;;
   "libo2cb/o2cb.7" ) CONFIG_FILES="$CONFIG_FILES libo2cb/o2cb.7" ;;
   "vendor/common/ocfs2-tools.spec-generic" ) CONFIG_FILES="$CONFIG_FILES vendor/common/ocfs2-tools.spec-generic" ;;
   "ocfs2console/blkid/blkid_types.h" ) CONFIG_COMMANDS="$CONFIG_COMMANDS ocfs2console/blkid/blkid_types.h" ;;
